apiVersion: v1
data:
  prometheus-additional.yaml: LSBqb2JfbmFtZTogJ25vZGVfZXhwb3J0ZXJfbWV0cmljcycKICBzY3JhcGVfaW50ZXJ2YWw6IDVzCiAgc3RhdGljX2NvbmZpZ3M6CiAgICAtIHRhcmdldHM6IFsnMTkyLjE2OC44OC4xMDo5MTAwJ10=
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
