apiVersion: v1
data:
  prometheus-additional.yaml: LSBqb2JfbmFtZTogJ25vZGVfZXhwb3J0ZXJfbWV0cmljcycKICBzY3JhcGVfaW50ZXJ2YWw6IDVzCiAgc3RhdGljX2NvbmZpZ3M6CiAgICAtIHRhcmdldHM6IFsnMTkyLjE2OC44OC4xMDo5MTAwJ10KICAgIAotIGpvYl9uYW1lOiAnTWlrcm90aWsnCiAgc2NyYXBlX2ludGVydmFsOiAxMHMKICBzY3JhcGVfdGltZW91dDogMTBzCiAgc3RhdGljX2NvbmZpZ3M6CiAgICAtIHRhcmdldHM6CiAgICAgIC0gMTkyLjE2OC44OC4xICAjIFNOTVAgZGV2aWNlCiAgIG1ldHJpY3NfcGF0aDogL3NubXAKICAgcGFyYW1zOgogICAgIG1vZHVsZTogW21pa3JvdGlrXQogICByZWxhYmVsX2NvbmZpZ3M6CiAgICAgLSBzb3VyY2VfbGFiZWxzOiBbX19hZGRyZXNzX19dCiAgICAgICB0YXJnZXRfbGFiZWw6IF9fcGFyYW1fdGFyZ2V0CiAgICAgLSBzb3VyY2VfbGFiZWxzOiBbX19wYXJhbV90YXJnZXRdCiAgICAgICB0YXJnZXRfbGFiZWw6IGluc3RhbmNlCiAgICAgLSB0YXJnZXRfbGFiZWw6IF9fYWRkcmVzc19fCiAgICAgICByZXBsYWNlbWVudDogMTAuMTA2LjEzMy40MDo5MTE2ICAgIA==
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
