- job_name: 'node_exporter_metrics'
  scrape_interval: 5s
  static_configs:
    - targets: ['192.168.88.10:9100']
    
- job_name: 'Mikrotik'
  scrape_interval: 10s
  scrape_timeout: 10s
  static_configs:
    - targets:
      - 192.168.88.1  # SNMP device
   metrics_path: /snmp
   params:
     module: [mikrotik]
   relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: 10.106.133.40:9116
